services:
  hono-server-db:
    image: postgres
    container_name: hono-server-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
      POSTGRES_DB: hono-server-db
    volumes:
      - postgres:/data/postgres
    networks:
      - hono-network

networks:
  hono-network:
    driver: bridge

volumes:
  postgres:
