services:
  hono-server:
    build:
      context: .
    container_name: hono-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - hono-network
    restart: always

  caddy:
    image: caddy/caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - hono-network
    depends_on:
      - hono-server
    restart: always

networks:
  hono-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
